# Camera Configuration
# This file was auto-generated by fix_camera.py

WORKING_CAMERA_INDEX = 0
WORKING_BACKEND = 700  # DirectShow (Windows native)

# How to use in your code:
# cap = cv2.VideoCapture(WORKING_CAMERA_INDEX, WORKING_BACKEND)
