"""
Camera Diagnostic and Fix Tool
Helps identify and resolve camera access issues
"""
import cv2
import numpy as np
import time

print("="*70)
print("CAMERA DIAGNOSTIC TOOL")
print("="*70)

# Try different camera backends
backends = [
    (cv2.CAP_DSHOW, "DirectShow (Windows native)"),
    (cv2.CAP_MSMF, "Microsoft Media Foundation"),
    (cv2.CAP_ANY, "Auto-detect"),
]

working_backend = None
working_index = None

print("\nStep 1: Testing camera backends...\n")

for camera_index in [0, 1, 2]:
    for backend_id, backend_name in backends:
        print(f"Testing Camera {camera_index} with {backend_name}...", end=" ")
        
        try:
            cap = cv2.VideoCapture(camera_index, backend_id)
            
            if cap.isOpened():
                # Try to read a frame
                ret, frame = cap.read()
                
                if ret and frame is not None:
                    print(f"✓ WORKING! Resolution: {frame.shape[1]}x{frame.shape[0]}")
                    
                    if working_backend is None:
                        working_backend = backend_id
                        working_index = camera_index
                        print(f"  → This will be used as default")
                    
                    cap.release()
                    time.sleep(0.5)  # Give camera time to release
                else:
                    print("❌ Can't read frames")
                    cap.release()
            else:
                print("❌ Can't open")
        except Exception as e:
            print(f"❌ Error: {e}")

print("\n" + "="*70)

if working_backend is None:
    print("❌ NO WORKING CAMERA FOUND!")
    print("\nPossible solutions:")
    print("1. Close any apps using the camera (Zoom, Teams, Skype, etc.)")
    print("2. Check Windows Camera Privacy Settings:")
    print("   - Open Settings → Privacy → Camera")
    print("   - Enable 'Allow apps to access your camera'")
    print("   - Enable 'Allow desktop apps to access your camera'")
    print("3. Restart your computer")
    print("4. Update camera drivers")
    print("5. Try unplugging and replugging camera (if external)")
    
else:
    print(f"✓ WORKING CAMERA FOUND!")
    print(f"  Camera Index: {working_index}")
    print(f"  Backend: {[name for bid, name in backends if bid == working_backend][0]}")
    
    print("\n" + "="*70)
    print("Step 2: Live Camera Test")
    print("="*70)
    print("Opening camera for live test...")
    print("Press Q to quit, SPACE to take a test photo")
    
    cap = cv2.VideoCapture(working_index, working_backend)
    
    # Set camera properties for better performance
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
    cap.set(cv2.CAP_PROP_FPS, 30)
    
    frame_count = 0
    
    while True:
        ret, frame = cap.read()
        
        if not ret:
            print("❌ Failed to read frame!")
            break
        
        frame_count += 1
        
        # Display info on frame
        cv2.putText(frame, f"Camera {working_index} - Press Q to quit, SPACE for photo", 
                    (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
        cv2.putText(frame, f"Frames: {frame_count}", (10, 60),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
        cv2.putText(frame, "Camera is WORKING!", (10, frame.shape[0] - 20),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
        
        cv2.imshow("Camera Test", frame)
        
        key = cv2.waitKey(1) & 0xFF
        
        if key == ord('q'):
            print(f"\n✓ Camera test complete! Read {frame_count} frames successfully.")
            break
        elif key == ord(' '):
            filename = f"test_photo_{int(time.time())}.jpg"
            cv2.imwrite(filename, frame)
            print(f"✓ Photo saved: {filename}")
    
    cap.release()
    cv2.destroyAllWindows()
    
    print("\n" + "="*70)
    print("CREATING FIX SCRIPT...")
    print("="*70)
    
    # Create a configuration file
    fix_code = f"""# Camera Configuration
# This file was auto-generated by fix_camera.py

WORKING_CAMERA_INDEX = {working_index}
WORKING_BACKEND = {working_backend}  # {[name for bid, name in backends if bid == working_backend][0]}

# How to use in your code:
# cap = cv2.VideoCapture(WORKING_CAMERA_INDEX, WORKING_BACKEND)
"""
    
    with open("camera_config.py", "w") as f:
        f.write(fix_code)
    
    print("✓ Created: camera_config.py")
    print(f"  → Use: cap = cv2.VideoCapture({working_index}, {working_backend})")
    
    print("\n" + "="*70)
    print("NEXT STEPS:")
    print("="*70)
    print("Your camera is working! To fix recognition.py:")
    print("")
    print("Option 1: Update recognition.py automatically")
    print("  Run: python apply_camera_fix.py")
    print("")
    print("Option 2: Manual fix")
    print(f"  Replace: cap = cv2.VideoCapture(0)")
    print(f"  With:    cap = cv2.VideoCapture({working_index}, {working_backend})")
    print("")
    
print("\n" + "="*70)
print("DIAGNOSTIC COMPLETE")
print("="*70)
